version: '3'

networks:
  delectatech:

services:

  # nginx
  nginx-delectatech-service:
    image: nginx:stable-alpine
    container_name: nginx-delectatech-container
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-delectatech-service
      - mysql-delectatech-service
    tty: true
    networks:
      - delectatech

  # php
  php-delectatech-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-delectatech-container
    ports:
      - "9000:9000"
    volumes:
      - ./code:/var/www/project
    networks:
      - delectatech

  # mysql
  mysql-delectatech-service:
    image: mysql:8
    container_name: mysql-delectatech-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
    networks:
      - delectatech
